---
- name: "tumbumer.user: check os version"
  fail:
    msg: "OS must be Ubuntu 20.04 Focal Fossa"
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_release == "focal")

- name: "tumbumer.user: set up default home directory permissions"
  become: true
  lineinfile:
    dest: /etc/login.defs
    regexp: "^UMASK"
    line: "UMASK    077"
  when: tumbumer_user_is_home_dir_private is defined and tumbumer_user_is_home_dir_private

- name: "tumbumer.user: set up default home files permissions"
  become: true
  file:
    path: "/etc/skel/{{ item }}"
    state: file
    mode: 0600
  with_items:
  - ".bash_logout"
  - ".bashrc"
  - ".profile"
  when: tumbumer_user_is_home_dir_private is defined and tumbumer_user_is_home_dir_private

- name: "tumbumer.user: manage"
  become: true
  user:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    remove: "{{ item.remove | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    createhome: "{{ item.createhome | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
  with_items: "{{ tumbumer_user_list | default({}) }}"

- name: "tumbumer.user: force to password change"
  become: true
  shell: "/usr/bin/chage -d0 {{ item }}"
  with_items: "{{ tumbumer_user_force_change_password_list | default({}) }}"
  when: tumbumer_user_force_change_password_list is defined

- name: "tumbumer.user: update authorized_key"
  become: true
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
    state: present
    exclusive: yes
  with_items: "{{ tumbumer_user_list | default({}) }}"
  when: item.ssh_public_key is defined

- name: "tumbumer.user: get home dir"
  shell: "set -eo pipefail && egrep '^{{ item.name }}:' /etc/passwd | awk -F: '{ print $6 }'"
  changed_when: false
  register: tumbumer_user_home
  with_items: "{{ tumbumer_user_list | default({}) }}"
  when: item.bashrc is defined

- name: "tumbumer.user: update ~/.bashrc"
  become: true
  blockinfile:
    dest: "{{ item.stdout }}/.bashrc"
    block: "{{ item.item.bashrc }}"
  with_items: "{{ tumbumer_user_home.results | default({}) }}"
  when: item.stdout is defined
